# Generated by Django 5.1.2 on 2025-02-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connecttransaction',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
