# Generated by Django 5.1.2 on 2024-10-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='extent_max_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='extent_max_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='extent_min_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='extent_min_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
