# Generated by Django 5.1.2 on 2024-12-18 19:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_server_extent_max_x_alter_server_extent_max_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='layer',
            name='type',
            field=models.CharField(choices=[('point', 'Point'), ('polyline', 'Polyline'), ('polygon', 'Polygon')], max_length=10),
        ),
    ]
