# Generated by Django 5.1.2 on 2025-04-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_downloadrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrecord',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downloadrecord',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
