# Generated by Django 5.1.2 on 2025-04-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_downloadrecord_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrecord',
            name='zoom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
