# Generated by Django 5.1.2 on 2025-06-03 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_downloadrecord_zoom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialReferenceSystem',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Spatial Reference System',
                'verbose_name_plural': 'Spatial Reference Systems',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='downloadrecord',
            options={'ordering': ['-downloaded_at']},
        ),
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['server__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='download_method',
            field=models.CharField(choices=[('point', 'Point-based'), ('bbox', 'Bounding box'), ('nearby', 'Nearby layers')], default='point', help_text='Method used to select download area', max_length=20),
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='feature_count',
            field=models.IntegerField(blank=True, help_text='Number of features included in this download', null=True),
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='srid',
            field=models.IntegerField(blank=True, help_text='Spatial Reference System ID used for this download', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='error_count',
            field=models.IntegerField(default=0, help_text='Number of consecutive errors encountered'),
        ),
        migrations.AddField(
            model_name='layer',
            name='error_message',
            field=models.TextField(blank=True, help_text='Details of the last error encountered'),
        ),
        migrations.AddField(
            model_name='layer',
            name='last_checked',
            field=models.DateTimeField(blank=True, help_text='When this layer was last checked for availability', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='last_successful_access',
            field=models.DateTimeField(blank=True, help_text='When this layer last responded successfully', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('intermittent', 'Intermittent'), ('inactive', 'Inactive'), ('unknown', 'Unknown')], default='unknown', help_text='Current availability status of this layer', max_length=20),
        ),
        migrations.AddIndex(
            model_name='downloadrecord',
            index=models.Index(fields=['user', '-downloaded_at'], name='core_downlo_user_id_b9eae9_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadrecord',
            index=models.Index(fields=['layer', '-downloaded_at'], name='core_downlo_layer_i_86acd6_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadrecord',
            index=models.Index(fields=['downloaded_at'], name='core_downlo_downloa_347ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='layer',
            index=models.Index(fields=['status'], name='core_layer_status_c640c5_idx'),
        ),
        migrations.AddIndex(
            model_name='layer',
            index=models.Index(fields=['last_checked'], name='core_layer_last_ch_0dafdc_idx'),
        ),
        migrations.AddIndex(
            model_name='layer',
            index=models.Index(fields=['server', 'type'], name='core_layer_server__1a1644_idx'),
        ),
    ]
