# Generated by Django 5.1.2 on 2025-06-30 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_spatialreferencesystem_alter_downloadrecord_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpatialReferenceSystem',
        ),
        migrations.RemoveIndex(
            model_name='downloadrecord',
            name='core_downlo_user_id_b9eae9_idx',
        ),
        migrations.RemoveIndex(
            model_name='downloadrecord',
            name='core_downlo_layer_i_86acd6_idx',
        ),
        migrations.RemoveIndex(
            model_name='downloadrecord',
            name='core_downlo_downloa_347ba3_idx',
        ),
        migrations.RemoveIndex(
            model_name='layer',
            name='core_layer_status_c640c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='layer',
            name='core_layer_last_ch_0dafdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='layer',
            name='core_layer_server__1a1644_idx',
        ),
        migrations.RemoveField(
            model_name='downloadrecord',
            name='download_method',
        ),
        migrations.RemoveField(
            model_name='downloadrecord',
            name='feature_count',
        ),
        migrations.RemoveField(
            model_name='downloadrecord',
            name='srid',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='error_count',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='last_checked',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='last_successful_access',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='status',
        ),
    ]
