# Generated by Django 5.1.2 on 2025-12-28 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_spatialreferencesystem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLayerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_count', models.PositiveIntegerField(default=1)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='core.layer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-download_count', '-last_used'],
                'unique_together': {('user', 'layer')},
            },
        ),
    ]
