# Generated by Django 5.2.8 on 2025-12-16 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_spatialreferencesystem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrecord',
            name='bbox_max_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='bbox_max_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='bbox_min_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='bbox_min_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='feature_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='file_format',
            field=models.CharField(default='dxf', max_length=10),
        ),
        migrations.AddField(
            model_name='layer',
            name='feature_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='last_validated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='server',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='server',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='last_validated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='LayerCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('fields_json', models.JSONField(blank=True, null=True)),
                ('sample_features_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('layer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cache', to='core.layer')),
            ],
        ),
        migrations.CreateModel(
            name='LayerValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('triggered_by', models.CharField(default='manual', max_length=50)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='core.layer')),
            ],
        ),
        migrations.CreateModel(
            name='UserLayerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_count', models.IntegerField(default=0)),
                ('last_downloaded', models.DateTimeField(blank=True, null=True)),
                ('first_downloaded', models.DateTimeField(auto_now_add=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='core.layer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'layer')},
            },
        ),
    ]
