# Generated by Django 5.1.2 on 2025-12-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userlayerpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlayerpreference',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
