# Generated by Django 5.2.8 on 2025-12-17 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_downloadrecord_bbox_max_x_downloadrecord_bbox_max_y_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlayerpreference',
            old_name='first_downloaded',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='userlayerpreference',
            name='custom_name',
        ),
        migrations.RemoveField(
            model_name='userlayerpreference',
            name='is_hidden',
        ),
        migrations.AddField(
            model_name='userlayerpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userlayerpreference',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.layer'),
        ),
        migrations.AlterField(
            model_name='userlayerpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userlayerpreference',
            index=models.Index(fields=['user', '-download_count'], name='core_userla_user_id_4997f7_idx'),
        ),
        migrations.AddIndex(
            model_name='userlayerpreference',
            index=models.Index(fields=['user', '-last_downloaded'], name='core_userla_user_id_afaf3f_idx'),
        ),
    ]
