# Generated by Django 5.1.2 on 2025-02-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connects',
            field=models.IntegerField(default=0),
        ),
    ]
